### ISSUE TITLE
Fix potential security vulnerabilities dependencies on package.json

### ISSUE THREAD

**Issue by enesacikoglu** [enesacikoglu/SpringBootAngular4Crud#3]

**Comment by fclk1212** [comment]
i wantto fix the issue

**Comment by enesacikoglu** [comment]
> i wantto fix the issue

Thanks it is on you.

**Comment by fclk1212** [comment]
please, give me more details/logs for the issue

**Comment by enesacikoglu** [comment]
> please, give me more details/logs for the issue

please run "npm install" on package.json dir you will see details.
